### ISSUE TITLE
Implement angular 2 new naming conventions

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-js-blocks#130]
**General Naming Guidelines**
- [x] Implement 'igx' as a selector prefix (dash separator)
- [x] Naming: follow a pattern that describes the symbol's feature then its type. The recommended pattern is feature.type.ts (badge.component.ts)
- [x] Use dashes to separate words in the descriptive name. (Separate File Names with Dots and Dashes)
- [x] Use upper camel case for class names (export class IgxAvatar)
- [x] Add 'Igx' prefix to class names (export class IgxAvatar)
- [x] Do use consistent names for all pipes, named after their feature
- [x] Do name test specification files the same as the component they test (with a suffix of .spec; Example: badge.component.spec.ts) 
- [x] Prefixes for Directives - 
@Directive({
  selector: '[igxLabel]'
})

**Coding Conventions:**
- [x] use upper camel case when naming classes and interfaces (exceptionService to ExceptionService )
- [x] Do use lower camel case to name properties and methods
- [x] Use underscore for private properties (private _size: string)

**Comment by kdinev** [comment]
Can you provide a link in the description with the naming convention. This is for reference.

**Comment by IG-Stanimir-Dimitrov** [comment]
Implement '**igx**' as a selector prefix and align the code as per [the Angular style guide](https://angular.io/docs/ts/latest/guide/style-guide.html).
