### ISSUE TITLE
List swipe actions - design

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-js-blocks#157]
https://github.com/IgniteUI/warehouse-js-blocks/issues/2

**Comment by sbozalieva** [comment]
Detailed in the List Item Component Specification.

- [ ] The developer can add list-items to the list. 
- [ ] The citizen developer can group the list items with headers. 
- [ ] The citizen developer can support navigation (href-s) for the list-items. 
- [ ] The citizen developer can add swipe(left and right) gestures to the list-items that reveal actions. 
- [ ] The citizen developer can add a expand and collapse for a list-tem. 
- [ ] The citizen developer can add one, two or three lines of text. 
- [ ] The citizen developer can customize the list-items adding custom elements: 
- Toggle 
- Checkbox 
- Inputs 
- Icons 
- Avatar 
- Badge
- [ ] The citizen developer can left and right align the elements. 
- [ ] The citizen developer has all ARIA tags that apply.

**Comment by IG-Stanimir-Dimitrov** [comment]
Design is complete.
New dev task created - List item implementation #217
