### ISSUE TITLE
Create IndigoStudio asset libraries for Material Theme

### ISSUE THREAD

**Issue by SDinev** [IgniteUI/igniteui-js-blocks#184]
Start asset libraries for IndigoStudio, consisting of the Material Theme elements. This will be great for visual designers so they can quickly create mockups/prototypes with our components, ensuring easier hand-off to front-end developers.

**Comment by IG-Stanimir-Dimitrov** [comment]
Research existing Indigo Studio code generation capabilities and check if we can use it for JS Blocks.

**Comment by kdinev** [comment]
There is now a repo for this. Move the issues there.
https://github.com/IgniteUI/js-blocks-ui-kits
