### ISSUE TITLE
[Dev productivity] Animations library 

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-js-blocks#252]
Implement Angular animations library to handle animations outside CSS

**Comment by IG-Stanimir-Dimitrov** [comment]
@simeonoff, can we close this issue now that the new animation library is committed to the repo?

**Comment by simeonoff** [comment]
@IG-Stanimir-Dimitrov documentation needs to be done first.

**Comment by IG-Stanimir-Dimitrov** [comment]
Docs have been added to [animation folders](https://github.com/IgniteUI/igniteui-js-blocks/tree/master/src/animations).
Library readme is also [available](https://github.com/IgniteUI/igniteui-js-blocks/blob/master/src/animations/README.md).

**Comment by kdinev** [comment]
@IG-Stanimir-Dimitrov @simeonoff Would the animation library be moved to its own repository?

**Comment by SDinev** [comment]
I think it's better if we put it in a separate repo and make some noise with it in social media channels (with a small landing page, possibly, to showcase what it is), include it in our newsletter, etc..

**Comment by kdinev** [comment]
@SDinev Agreed!
