### ISSUE TITLE
Move JSB Specs to GitHub Wiki

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-js-blocks#285]
Specifications:
- [x] avatar 
- [x] badge
- [x] carousel  
- [x] list  
- [x] navbar 
- [x] tabbar  
- [x] dialog 
- [x] snackbar 
- [x] toast
- [x] navigation drawer 
- [x] radio 
- [x] checkbox 
- [x] switch 
- [x] linear progress bar 
- [x] circular progress bar
- [x] icon 
- [x] card
- [x] igxButton (Directive)
- [x] igxFiltering (Directive)
- [x] igxRipple (Directive)
- [x] igxInput (Directive)
- [x] igxLabel (Directive)
- [x] igxLayout (Directive)

**Comment by petko5kov** [comment]
Tabbar online spec is based on this old spec: [Tab Bar spec.docx](https://github.com/IgniteUI/igniteui-js-blocks/files/754803/Tab.Bar.spec.docx)

**Comment by petko5kov** [comment]
List online spec is based on these specs: 
[List (5).docx](https://github.com/IgniteUI/igniteui-js-blocks/files/757788/List.5.docx)
[List Component Specification.docx](https://github.com/IgniteUI/igniteui-js-blocks/files/757790/List.Component.Specification.docx)

**Comment by petko5kov** [comment]
The modified old specs of tabbar and list
[Tab Bar spec.docx](https://github.com/IgniteUI/igniteui-js-blocks/files/758446/Tab.Bar.spec.docx)
[List old spec.docx](https://github.com/IgniteUI/igniteui-js-blocks/files/758447/List.old.spec.docx)
[List Component Specification.docx](https://github.com/IgniteUI/igniteui-js-blocks/files/758445/List.Component.Specification.docx)
