### ISSUE TITLE
http://igniteui.github.io/igniteui-js-blocks/ throws JS error

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-js-blocks#291]
### Description  
http://igniteui.github.io/igniteui-js-blocks/ throws JS error and the page does not fully load. The Warehouse app does not work too.

### Steps to reproduce  

1. Go to http://igniteui.github.io/igniteui-js-blocks/
2. Open Dev Tools

### Result  
JS Error appears:
Error: Cannot read property 'System' of undefined

### Expected result  
No errors should appear and the page should fully load.

### Attachments 
![capture](https://cloud.githubusercontent.com/assets/6439482/22324953/9a465738-e3b4-11e6-8e47-1a387c95cae0.PNG)

**Comment by rkaraivanov** [comment]
closed via #294
