### ISSUE TITLE
Naming Convention - Wiki: Component Specs

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-js-blocks#360]
### Description  
Component Specs in the Wiki are named in a different manner:

"...
igxButton
igxRipple
Linear Progress Bar
Circular Progress Bar
...
"

### Steps to reproduce  
Rename them following a naming convention. 

### Attachments  
https://github.com/IgniteUI/igniteui-js-blocks/wiki

**Comment by IG-Stanimir-Dimitrov** [comment]
All specs in the wiki have been renamed following the established convention. I am closing this issue now.
