### ISSUE TITLE
Missing README.md files

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-js-blocks#361]
### Description  

1. igx-navdrawer README.md is missing
2. igx-scroll README.md is missing
3. igx-linear-bar and igx-linear-bar should have separate README.md docs since they have separate wikis.

### Steps to reproduce  

1. Create igx-navdrawer README.md
2. Update igx-scroll Docs column as "Not Available"
3. Separate igx-linear-bar and igx-linear-bar README.md docs

**Comment by IG-Stanimir-Dimitrov** [comment]
The igx-scroll is a planned control for the future so we do not have README.md for it yet

**Comment by sbozalieva** [comment]
Okay then, we can update the Docs column it the the table as "Not Available".
