### ISSUE TITLE
README.md Template

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-js-blocks#362]
### Description  
All README.md files differ.

### Steps to reproduce  
Unify all README.md docs using a template.

### Template  
https://github.com/IgniteUI/igniteui-js-blocks/blob/4e92cbc35e40a86028e1bddc69d56defabdd8d4c/readme-template.md

**Comment by kdinev** [comment]
@sbozalieva Could you please pull the template into master?

**Comment by IG-Stanimir-Dimitrov** [comment]
[Readme template](https://github.com/IgniteUI/igniteui-js-blocks/blob/master/readme-template.md) is merged into master with pull request https://github.com/IgniteUI/igniteui-js-blocks/pull/363. Closing this issue.
