### ISSUE TITLE
NPM Version Mistake

### ISSUE THREAD

**Issue by JSMike** [IgniteUI/igniteui-js-blocks#369]
### Description  
I'm assuming the recent NPM publish was a mistake? the version jumped from 0.2.3 to 4.0.0. I'd assume the next version should be 0.2.4

### Steps to reproduce  
`npm view igniteui-js-blocks versions`

### Result  
`[ '0.2.1', '0.2.2', '0.2.3', '4.0.0' ]`

### Expected result  
`[ '0.2.1', '0.2.2', '0.2.3', '0.2.4' ]`

### Attachments  
N/A

**Comment by kdinev** [comment]
@JSMike The notes to the `4.0.0` tag is that we're bringing versioning in line with the Angular versioning. Versioning will from now on depend on what version of Angular it is developed against. This means that when Angular 5 is released, we will keep bumping up the major version 4 until we have the code working with Angular 5, and then the major version will become 5.

**Comment by JSMike** [comment]
ok thx
