### ISSUE TITLE
Module not found: Error: Can't resolve

### ISSUE THREAD

**Issue by JSMike** [IgniteUI/igniteui-js-blocks#370]
### Description  
The wrong relative path is being bundled in the NPM package for several files

* igniteui-js-blocks/bundles/igniteui-js-blocks.dev.js
* igniteui-js-blocks/bundles/igniteui-js-blocks.min.js
* igniteui-js-blocks/bundles/zero-blocks.min.js
* igniteui-js-blocks/buttonGroup/buttonGroup.component.js
* igniteui-js-blocks/checkbox/checkbox.component.js
* igniteui-js-blocks/grid/grid.component.js
* igniteui-js-blocks/grid/grid.component.d.js

### Steps to reproduce  
create new project with angular cli
npm install ignite-ui-js-blocks
add ignite-ui-js-blocks import to your app.module.ts
add a buttongroup dependency

### Result  
```
ERROR in ./~/igniteui-js-blocks/buttonGroup/buttonGroup.component.js
Module not found: Error: Can't resolve '../../src/directives/ripple.directive' in 'D:\dev\ng-ui-study\node_modules\igniteui-js-blocks\buttonGroup'
 @ ./~/igniteui-js-blocks/buttonGroup/buttonGroup.component.js 14:25-73
 @ ./~/igniteui-js-blocks/main.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

### Expected result  
webpack: Compiled successfully.

### Attachments  
N/A

Note: manually replacing `../../src/` with `..` temporarily resolves the issue, this appears to be an issue with your gulp build process.

**Comment by kdinev** [comment]
@JSMike Could you verify that you're not reproducing these errors anymore?

**Comment by JSMike** [comment]
Sure, I'm at work now, I'll test when I get home.

**Comment by JSMike** [comment]
This looks good. There are still other issues with your build system though. I'll be creating some more issues and PR's over the weekend when I have time to organize my notes. (FYI, I used this library as part of a college project to compare UI component libraries for Angular)

**Comment by kdinev** [comment]
@JSMike Awesome! Could you let us know what your findings are?
