### ISSUE TITLE
Update IO pages with the new demos

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-js-blocks#372]
Update the io pages with the new demos

**Comment by kdinev** [comment]
@IG-Stanimir-Dimitrov This needs to be done soon, as the old demo page doesn't even load at the moment!

**Comment by IG-Stanimir-Dimitrov** [comment]
@kdinev, once the new demos small glitches are fixed we will update the page. We saw that io page issue yesterday with @rkaraivanov and will fix it even before the update.

**Comment by zdrawku** [comment]
Demos are updated, along with readme.md
