### ISSUE TITLE
Warehouse sample application not working

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-js-blocks#383]
### Description  
Warehouse sample application is not working

### Steps to reproduce  
Open https://igniteui.github.io/warehouse-js-blocks/ 

### Result  
The application does not work
error: get https://igniteui.github.io/warehouse-js-blocks/@angular/animations 404 (Not Found)

### Expected result  
The load the sample application

**Comment by rkaraivanov** [comment]
Closed by IgniteUI/warehouse-js-blocks#10
