### ISSUE TITLE
Create igniteui-js-block-quickstart application

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-js-blocks#406]
We need to create a quickstart app for Angular users interested in Ignite UI JS Blocks controls so they have a solid starting point when interacting with our suite.

- [x] Fork the [the angular quickstart](https://github.com/angular/quickstart) and update it with the JS Blocks references.
- [x] Update the views with sample JS Blocks controls.
- [x] Add the quickstart app in a new **IgniteUI/igniteui-js-blocks-quickstart** repo. 
- [x] Update the JS Blocks repo documentation [readme ](https://github.com/IgniteUI/igniteui-js-blocks/blob/master/README.md) with the quickstart app details.

**Comment by hanastasov** [comment]
The app is available at https://github.com/IgniteUI/igniteui-js-blocks-quickstart. Typescript version seems to be causing issues for the e2e tests, will try downgrading to see if it fixes that.

**Comment by IG-Stanimir-Dimitrov** [comment]
@hanastasov , thanks - I am closing this issue now.

Any missing features/bugs will be added directly in the [quickstart app repo](https://github.com/IgniteUI/igniteui-js-blocks-quickstart).
