### ISSUE TITLE
Demos not working on iOS browsers

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-js-blocks#459]
### Description  
The JS Blocks samples are not loading on iOS devices

### Steps to reproduce  
Open http://139.59.168.161/demos/ on iPhone/iPad

### Result  
The app hangs on loading screen

### Expected result  
Samples to load

**Comment by simeonoff** [comment]
This issue was resolved with #437

**Comment by IG-Stanimir-Dimitrov** [comment]
@simeonoff , thanks - will close the issue when we redeploy the samples.

**Comment by IG-Stanimir-Dimitrov** [comment]
@zdrawku , can you update the samples with a newer demo?
