### ISSUE TITLE
Update demo application to also display control documentation

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-js-blocks#462]
### Description 

The JS Blocks demo app currently holds control samples and styles guide. However, it need to be updated to also display control readme so it can also be used as a reference site for developers.

### Required Implementation

1. Add Documentation section in the navDrawer that lists all controls with their doc pages
2. Update the application to read the control readme.md files from GitHub and parse the content directly in the application
3. Add Documentation button on every control page that points to the corresponding component documentation page

**Comment by simeonoff** [comment]
Since we will be removing the demos folder from the project, all future requests regarding documentation in the samples pages should be done under the [DocFX repo](https://github.com/IgniteUI/igniteui-docfx).
