### ISSUE TITLE
[igx-slider] Range Slider Thumps collapsing

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-js-blocks#463]
### Description  
The Range Slider has a left and a right thumb that appear during interaction to both ease the end user navigation and also display the current slider value. These need to stay expanded whenever the user interacts with the control but the range thumbs currently hide after several seconds.

### Steps to reproduce  

1. `npm start` the current demo application and navigate to the slider sample
2.  Drag the range slider nobs so the thumbs appear and then disappear

### Result 
Thumbs appear and disappear while user is still interacting with the control

![](http://i.imgur.com/Zh8vmLP.gif)

### Expected result  
Thumbs to stay visible during the whole interaction

**Comment by SlavUI** [comment]
@tiliev  Assigning it to you to resolve the issue in Sprint 3

**Comment by hanastasov** [comment]
Already fixed. See how control behaves at https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider.html. The thumb hides only after the user has released it.
