### ISSUE TITLE
Grid column object refactoring

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-js-blocks#481]
### Description  
Refactor the `igx-grid` column objects.

**Comment by kdinev** [comment]
@rkaraivanov Should I close this issue? My understanding is that after investigation the column object looks good.

**Comment by rkaraivanov** [comment]
Yes, the column component does not seem to need any serious changes right now.

**Comment by lucianoybanez** [comment]
Hi, 
        Is it possible to use an object inside other object for grid columns ? Example:
`<igx-column field="Department.Name" header="Department" >` or just could be an DTO object?

Thanks,
