### ISSUE TITLE
Circular progress bar does not update visually when setting the value through the API

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-js-blocks#484]
### Description  
Circular progress bar does not update visually when setting the value through the component API.

### Steps to reproduce  

1. Create a circular progress bar and get a reference to it.
2. After component view initialization update the `value` property

### Result  
The progress bar should update visually based on the new value.

### Expected result  
The value is updated but not reflected visually.

**Comment by SlavUI** [comment]
Hi is there any update on the issue :)

**Comment by SlavUI** [comment]
@zdrawku Hi Zdravko since Aleks is off can you please review the issue ?

**Comment by SlavUI** [comment]
This is to be resolved when we redo the Demos
