### ISSUE TITLE
Getting Started Update

### ISSUE THREAD

**Issue by SDinev** [IgniteUI/igniteui-js-blocks#487]
The [Getting Started Page](https://www.infragistics.com/products/ignite-ui-angular/getting-started)  needs to be updated with more information. 
- [x]  Mention importing HammerJS and @Types/HammerJS
- [x]  Explain modifying the angular-cli.json file to include the styling for Ignite UI for Angular
- [x]  Change the navbar with another component ( for example: datepicker with some additional design)
- [x]  Clear unnecessary imports

**Comment by hanastasov** [comment]
https://umbraco.staging.infragistics.local/products/ignite-ui-angular/getting-started

**Comment by hanastasov** [comment]
Changes are available on staging.

**Comment by MikeTechSpeak** [comment]
Adding the staging link here:
https://staging.infragistics.local/products/ignite-ui-angular/getting-started

Any time frame of when this will go live?

**Comment by jVanZwieten** [comment]
<h1/> causes an issue. It should be </h1>.

**Comment by hanastasov** [comment]
In Usage section Ignite **ui** needs to be capitalized.

**Comment by dianj** [comment]
The fixes are applied:
https://staging.infragistics.local/products/ignite-ui-angular/getting-started

**Comment by SDinev** [comment]
Two things:
 - [ ] Add a screenshot for the expected final result, so people know if they've done the steps right - Spasimir
 - [ ] figure out a way to avoid this: 
`<img width="300" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">` 
Replace it with a link to an image, for brevity and improved legibility

**Comment by StefanIvanov** [comment]
I totally skipped this point "please make sure that HammerJS and @Types/hammerJS are also installed in your app" and after coming back to it I installed them in my projects folder but apparently it should be done in the folder of the particular project. I think the initial paragraphs have to be restructured because there is critical information in them. 
- [ ] Add color coding to the code snippets to make them more readable

**Comment by hanastasov** [comment]
Restructure the paragraphs in what ways ?

**Comment by StefanIvanov** [comment]
Bullet list the two "dependencies" as they are the initial steps for example with a font treatment to make them stand out more e.g. bold or larger font size

**Comment by MikeTechSpeak** [comment]
Can we get either the embedded plunkr, link to plunkr or JSFiddle back in. Being able to modify a live sample is a very easy way to learn, as well as to demo to customers. It was in the pre-release, and it was yanked out. Was there a reason for it being yanked?

**Comment by kdinev** [comment]
@MikeTechSpeak Marketing requested that we remove plunkr.

**Comment by MikeTechSpeak** [comment]
Fair enough, but who and why? Because the embedded code is extremely useful. I believe plukr looked a little off because I think they had embedded ads. Which if that is why that is a valid reason. But can't we still use jsFiddle instead then?

**Comment by simeonoff** [comment]
We can still have both. Our samples will live both on plunkr and on our server. We will just provide a sample link to plunkr where people can play around with it.

**Comment by kdinev** [comment]
Please close this issue and create a new one, so we can put it in planning.

**Comment by kdinev** [comment]
@MikeTechSpeak @dianj Please abstain from posting links in the public issues that are not publicly accessible.

**Comment by SDinev** [comment]
Alright. 
Arguably, we'll have an updated Getting Started with our CLI. Until then, let's have some final quick fixes to the current version and update the website. 
 - [ ] create a separate code box afte the `npm install igniteui-js-blocks` for the hammerjs and @types/hammerjs dependencies. Include a `//comment` in the box explaining that these are dependencies. 
 - [ ] Bold or otherwise single out names of files from the rest of the text - like "angular-cli.json". This will increase visibility as well as overall legibility
 - [ ] in the codebox for angular-cli.json, add 
`      "scripts": ["../node_modules/hammerjs/hammer.min.js"],`
without this line, the code from the getting started does not execute properly
 - [ ] in all codeboxes, include comments to annotate where we're adding on top of the Angular CLI. Include color coding if possible, to be consistent with the documentation code boxes.
- [ ] include a screenshot for the expected end result at the end of the article (preview in image):
![preview-getting-started](https://user-images.githubusercontent.com/13866657/33992451-4c43eb7a-e0db-11e7-9c64-c22f4a951dff.png)
 - [ ] change Angular logo with Infragistics logo
 - [ ] change app title from "app" to "Ignite UI for Angular"
including ig logo and images: 

[InfragisticsLogo.zip](https://github.com/IgniteUI/igniteui-js-blocks/files/1559153/InfragisticsLogo.zip)

![ignite-screen-2](https://user-images.githubusercontent.com/13866657/33992505-9148f184-e0db-11e7-8e0c-3c9bee7a7d82.png)

![ignite_screen-1](https://user-images.githubusercontent.com/13866657/33992507-919b0bae-e0db-11e7-8243-12ea3727e33b.png)
