### ISSUE TITLE
Rename zero-blocks.css

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-js-blocks#502]
### Description  
Current css file name is `zero-blocks.css`, but it doesn't match repo name.

### Expected result  
According to the [blog](https://www.infragistics.com/community/blogs/b/infragistics/posts/ignite-ui-github-repo-name-changes), this repo name is going to be **igniteui-angular**.

So I think `igniteui-angular.css` is better.

**Comment by kdinev** [comment]
@tkiryu This change will take place on January 15th.
